import sys

# DATADOG CREDENTIALS
DATADOG_API_KEY = sys.argv[1]
DATADOG_APP_KEY = sys.argv[2]

# AWS CREDENTIALS
AWS_ACCESS_KEY_ID = sys.argv[3]
AWS_SECRET_ACCESS_KEY = sys.argv[4]

# AWS S3 BUCKET NAME
S3_BUCKET_NAME = sys.argv[5]
